@startuml

legend top left
    | Color | Type |
    |<#LightGreen>| Android Platform |
endlegend

rectangle lunch #black;text:white [
$ . ./build/envsetup.sh
$ lunch
  ...
  59. ncar_x86-userdebug
  ...
]

' Android Platform
folder generic_car_common_overlay #LightGreen[
device/generic/car/common/overlay
]

file aosp_car_emulator.mk #LightGreen [
aosp_car_emulator.mk

device/generic/car/emulator/
]
file aosp_x86.mk #LightGreen [
aosp_x86.mk 

build/target/product/
]
file aosp_BoardConfig.mk #LightGreen [
BoardConfig.mk

device/generic/car/generic_car_x86/
]

' New device stuff
folder ncar [
device/nkh-lab/ncar/
]

file AndroidProducts.mk
file ncar_x86.mk
file BoardConfig.mk [
ncar_x86/BoardConfig.mk
]

note top of AndroidProducts.mk : Start point to add a new device

ncar -down-> AndroidProducts.mk : contains
ncar -down-> ncar_x86.mk : contains
ncar -down-> BoardConfig.mk : contains


AndroidProducts.mk -> ncar_x86.mk : PRODUCT_MAKEFILES
AndroidProducts.mk -left-> lunch : COMMON_LUNCH_CHOICES

ncar_x86.mk --> generic_car_common_overlay : PRODUCT_PACKAGE_OVERLAYS
ncar_x86.mk --> aosp_car_emulator.mk : inherit-product
ncar_x86.mk --> aosp_x86.mk : inherit-product
ncar_x86.mk -right-> BoardConfig.mk : PRODUCT_DEVICE

BoardConfig.mk --> aosp_BoardConfig.mk : include

@enduml 